version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./flights/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  flights:
    build: ./flights
    depends_on:
      - postgres
    volumes:
      - ./flights:/usr/src/flights

  orchestrator:
    build: ./orchestrator
    depends_on:
      - flights
    ports:
      - "8080:8080"
    volumes:
      - ./orchestrator:/usr/src/orchestrator

  web:
    build: ./web
    ports:
      - "80:80"

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    volumes:
      - ./flights/pgadmin4/servers.json:/pgadmin4/servers.json
